language: php

php:
    - '7.4'

script:
    - make ci

install:
    - composer install

after_success:
    - bash <(curl -s https://codecov.io/bash) -f "build/coverage.xml"

env:
    global:
        - XDEBUG_MODE=coverage
